-- MySQL Script generated by MySQL Workbench
-- 07/23/15 22:04:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sangreTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sangreTipo` (
  `sangId` INT NOT NULL COMMENT '',
  `sanDes` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`sangId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sexo` (
  `sexoId` INT NOT NULL COMMENT '',
  `sexDes` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`sexoId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jornada` (
  `jornId` INT NOT NULL COMMENT '',
  `jorDes` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`jornId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`destalleMatricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`destalleMatricula` (
  `matrId` INT NOT NULL COMMENT '',
  `asigId` INT NULL COMMENT '',
  `aulaId` INT NULL COMMENT '',
  `alumId` INT NULL COMMENT '',
  `jornadaId` INT NULL COMMENT '',
  `asignaturas_asigId` INT NOT NULL COMMENT '',
  `asignaturas_docente_doceId` INT NOT NULL COMMENT '',
  `asignaturas_docente_sexo_sexoId` INT NOT NULL COMMENT '',
  `Jornada_jornId` INT NOT NULL COMMENT '',
  `destalleMatricula_matrId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_asigId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_docente_doceId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_docente_sexo_sexoId` INT NOT NULL COMMENT '',
  `destalleMatricula_Jornada_jornId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`matrId`, `asignaturas_asigId`, `asignaturas_docente_doceId`, `asignaturas_docente_sexo_sexoId`, `Jornada_jornId`, `destalleMatricula_matrId`, `destalleMatricula_asignaturas_asigId`, `destalleMatricula_asignaturas_docente_doceId`, `destalleMatricula_asignaturas_docente_sexo_sexoId`, `destalleMatricula_Jornada_jornId`)  COMMENT '',
  INDEX `fk_destalleMatricula_Jornada1_idx` (`Jornada_jornId` ASC)  COMMENT '',
  CONSTRAINT `fk_destalleMatricula_Jornada1`
    FOREIGN KEY (`Jornada_jornId`)
    REFERENCES `mydb`.`Jornada` (`jornId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos` (
  `alumId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `encaId` INT NULL COMMENT '',
  `aluNom` VARCHAR(50) NOT NULL COMMENT '',
  `aludir` VARCHAR(100) NOT NULL COMMENT '',
  `alunac` DATE NOT NULL COMMENT '',
  `sangId` INT NOT NULL COMMENT '',
  `aluEnf` VARCHAR(100) NULL COMMENT '',
  `aluAle` VARCHAR(100) NULL COMMENT '',
  `aluDis` VARCHAR(100) NULL COMMENT '',
  `aluEst` VARCHAR(3) NULL COMMENT '',
  `aluSex` INT NULL COMMENT '',
  `sangreTipo_sangId` INT NOT NULL COMMENT '',
  `sexo_sexoId` INT NOT NULL COMMENT '',
  `destalleMatricula_matrId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_asigId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_docente_doceId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_docente_sexo_sexoId` INT NOT NULL COMMENT '',
  `destalleMatricula_Jornada_jornId` INT NOT NULL COMMENT '',
  `destalleMatricula_destalleMatricula_matrId` INT NOT NULL COMMENT '',
  `destalleMatricula_destalleMatricula_asignaturas_asigId` INT NOT NULL COMMENT '',
  `destalleMatricula_destalleMatricula_asignaturas_docente_doceId` INT NOT NULL COMMENT '',
  `destalleMatricula_destalleMatricula_asignaturas_docente_sexo_sexoId` INT NOT NULL COMMENT '',
  `destalleMatricula_destalleMatricula_Jornada_jornId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`alumId`, `sangreTipo_sangId`, `sexo_sexoId`, `destalleMatricula_matrId`, `destalleMatricula_asignaturas_asigId`, `destalleMatricula_asignaturas_docente_doceId`, `destalleMatricula_asignaturas_docente_sexo_sexoId`, `destalleMatricula_Jornada_jornId`, `destalleMatricula_destalleMatricula_matrId`, `destalleMatricula_destalleMatricula_asignaturas_asigId`, `destalleMatricula_destalleMatricula_asignaturas_docente_doceId`, `destalleMatricula_destalleMatricula_asignaturas_docente_sexo_sexoId`, `destalleMatricula_destalleMatricula_Jornada_jornId`)  COMMENT '',
  INDEX `fk_alumnos_sangreTipo_idx` (`sangreTipo_sangId` ASC)  COMMENT '',
  INDEX `fk_alumnos_sexo1_idx` (`sexo_sexoId` ASC)  COMMENT '',
  INDEX `fk_alumnos_destalleMatricula1_idx` (`destalleMatricula_matrId` ASC, `destalleMatricula_asignaturas_asigId` ASC, `destalleMatricula_asignaturas_docente_doceId` ASC, `destalleMatricula_asignaturas_docente_sexo_sexoId` ASC, `destalleMatricula_Jornada_jornId` ASC, `destalleMatricula_destalleMatricula_matrId` ASC, `destalleMatricula_destalleMatricula_asignaturas_asigId` ASC, `destalleMatricula_destalleMatricula_asignaturas_docente_doceId` ASC, `destalleMatricula_destalleMatricula_asignaturas_docente_sexo_sexoId` ASC, `destalleMatricula_destalleMatricula_Jornada_jornId` ASC)  COMMENT '',
  CONSTRAINT `fk_alumnos_sangreTipo`
    FOREIGN KEY (`sangreTipo_sangId`)
    REFERENCES `mydb`.`sangreTipo` (`sangId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_sexo1`
    FOREIGN KEY (`sexo_sexoId`)
    REFERENCES `mydb`.`sexo` (`sexoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_destalleMatricula1`
    FOREIGN KEY (`destalleMatricula_matrId` , `destalleMatricula_asignaturas_asigId` , `destalleMatricula_asignaturas_docente_doceId` , `destalleMatricula_asignaturas_docente_sexo_sexoId` , `destalleMatricula_Jornada_jornId` , `destalleMatricula_destalleMatricula_matrId` , `destalleMatricula_destalleMatricula_asignaturas_asigId` , `destalleMatricula_destalleMatricula_asignaturas_docente_doceId` , `destalleMatricula_destalleMatricula_asignaturas_docente_sexo_sexoId` , `destalleMatricula_destalleMatricula_Jornada_jornId`)
    REFERENCES `mydb`.`destalleMatricula` (`matrId` , `asignaturas_asigId` , `asignaturas_docente_doceId` , `asignaturas_docente_sexo_sexoId` , `Jornada_jornId` , `destalleMatricula_matrId` , `destalleMatricula_asignaturas_asigId` , `destalleMatricula_asignaturas_docente_doceId` , `destalleMatricula_asignaturas_docente_sexo_sexoId` , `destalleMatricula_Jornada_jornId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aportaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aportaciones` (
  `aporId` INT NOT NULL COMMENT '',
  `apades` VARCHAR(50) NOT NULL COMMENT '',
  `apacan` VARCHAR(45) NOT NULL COMMENT '',
  `Encargado_encaId` INT NOT NULL COMMENT '',
  `Encargado_aportaciones_aporId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`aporId`, `Encargado_encaId`, `Encargado_aportaciones_aporId`)  COMMENT '',
  INDEX `fk_aportaciones_Encargado1_idx` (`Encargado_encaId` ASC, `Encargado_aportaciones_aporId` ASC)  COMMENT '',
  CONSTRAINT `fk_aportaciones_Encargado1`
    FOREIGN KEY (`Encargado_encaId` , `Encargado_aportaciones_aporId`)
    REFERENCES `mydb`.`Encargado` (`encaId` , `aportaciones_aporId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Encargado` (
  `encaId` INT NOT NULL COMMENT '',
  `encNom` VARCHAR(50) NOT NULL COMMENT '',
  `encEstCiv` VARCHAR(50) NULL COMMENT '',
  `encTel` INT NOT NULL COMMENT '',
  `encDir` VARCHAR(100) NOT NULL COMMENT '',
  `encSex` INT NOT NULL COMMENT '',
  `encEst` VARCHAR(3) NULL COMMENT '',
  `aporId` INT NULL COMMENT '',
  `aportaciones_aporId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`encaId`, `aportaciones_aporId`)  COMMENT '',
  INDEX `fk_Encargado_aportaciones1_idx` (`aportaciones_aporId` ASC)  COMMENT '',
  CONSTRAINT `fk_Encargado_aportaciones1`
    FOREIGN KEY (`aportaciones_aporId`)
    REFERENCES `mydb`.`aportaciones` (`aporId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`docente` (
  `doceId` INT NOT NULL COMMENT '',
  `docNom` VARCHAR(50) NOT NULL COMMENT '',
  `DocDir` VARCHAR(100) NOT NULL COMMENT '',
  `doceSex` INT NULL COMMENT '',
  `docNac` DATE NOT NULL COMMENT '',
  `docNombramiento` VARCHAR(100) NOT NULL COMMENT '',
  `sexo_sexoId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`doceId`, `sexo_sexoId`)  COMMENT '',
  INDEX `fk_docente_sexo1_idx` (`sexo_sexoId` ASC)  COMMENT '',
  CONSTRAINT `fk_docente_sexo1`
    FOREIGN KEY (`sexo_sexoId`)
    REFERENCES `mydb`.`sexo` (`sexoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asignaturas` (
  `asigId` INT NOT NULL COMMENT '',
  `doceId` INT NULL COMMENT '',
  `NomAsi` VARCHAR(50) NOT NULL COMMENT '',
  `docente_doceId` INT NOT NULL COMMENT '',
  `docente_sexo_sexoId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`asigId`, `docente_doceId`, `docente_sexo_sexoId`)  COMMENT '',
  INDEX `fk_asignaturas_docente1_idx` (`docente_doceId` ASC, `docente_sexo_sexoId` ASC)  COMMENT '',
  CONSTRAINT `fk_asignaturas_docente1`
    FOREIGN KEY (`docente_doceId` , `docente_sexo_sexoId`)
    REFERENCES `mydb`.`docente` (`doceId` , `sexo_sexoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aportaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aportaciones` (
  `aporId` INT NOT NULL COMMENT '',
  `apades` VARCHAR(50) NOT NULL COMMENT '',
  `apacan` VARCHAR(45) NOT NULL COMMENT '',
  `Encargado_encaId` INT NOT NULL COMMENT '',
  `Encargado_aportaciones_aporId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`aporId`, `Encargado_encaId`, `Encargado_aportaciones_aporId`)  COMMENT '',
  INDEX `fk_aportaciones_Encargado1_idx` (`Encargado_encaId` ASC, `Encargado_aportaciones_aporId` ASC)  COMMENT '',
  CONSTRAINT `fk_aportaciones_Encargado1`
    FOREIGN KEY (`Encargado_encaId` , `Encargado_aportaciones_aporId`)
    REFERENCES `mydb`.`Encargado` (`encaId` , `aportaciones_aporId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aula` (
  `aulaId` INT NOT NULL COMMENT '',
  `aulDes` VARCHAR(45) NOT NULL COMMENT '',
  `destalleMatricula_matrId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`aulaId`, `destalleMatricula_matrId`)  COMMENT '',
  INDEX `fk_aula_destalleMatricula1_idx` (`destalleMatricula_matrId` ASC)  COMMENT '',
  CONSTRAINT `fk_aula_destalleMatricula1`
    FOREIGN KEY (`destalleMatricula_matrId`)
    REFERENCES `mydb`.`destalleMatricula` (`matrId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matricula` (
  `matrId` INT NOT NULL COMMENT '',
  `alumId` INT NULL COMMENT '',
  `matFecha` VARCHAR(45) NULL COMMENT '',
  `destalleMatricula_asignaturas_asigId` INT NOT NULL COMMENT '',
  `destalleMatricula_matrId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_docente_doceId` INT NOT NULL COMMENT '',
  `destalleMatricula_asignaturas_docente_sexo_sexoId` INT NOT NULL COMMENT '',
  `matFinal` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`matrId`, `destalleMatricula_asignaturas_asigId`, `destalleMatricula_matrId`, `destalleMatricula_asignaturas_docente_doceId`, `destalleMatricula_asignaturas_docente_sexo_sexoId`)  COMMENT '',
  INDEX `fk_matricula_destalleMatricula1_idx` (`destalleMatricula_matrId` ASC, `destalleMatricula_asignaturas_asigId` ASC, `destalleMatricula_asignaturas_docente_doceId` ASC, `destalleMatricula_asignaturas_docente_sexo_sexoId` ASC)  COMMENT '',
  CONSTRAINT `fk_matricula_destalleMatricula1`
    FOREIGN KEY (`destalleMatricula_matrId` , `destalleMatricula_asignaturas_asigId` , `destalleMatricula_asignaturas_docente_doceId` , `destalleMatricula_asignaturas_docente_sexo_sexoId`)
    REFERENCES `mydb`.`destalleMatricula` (`matrId` , `asignaturas_asigId` , `asignaturas_docente_doceId` , `asignaturas_docente_sexo_sexoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
